KingsOwnInstitute/Controllers/AttendeesController.cs
using KingsOwnInstitute.Data;
using KingsOwnInstitute.Data.Services;
using KingsOwnInstitute.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KingsOwnInstitute.Controllers
{
    public class AttendeesController : Controller
    {
        private readonly IAttendeesService _service;
        public AttendeesController(IAttendeesService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allAttendees = await _service.GetAllAsync();
            return View(allAttendees);
        }

        //Get: Attendee Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, DOB, Address")] Attendee attendee)
        {
            if (!ModelState.IsValid)
            {
                return View(attendee);
            }
            await _service.AddAsync(attendee);
            TempData["Success"] = "Attendee added successfully";
            return RedirectToAction(nameof(Index));
        }

        //Get: Attendee Edit
        public async Task<IActionResult> Edit(int id)
        {
            var attendeeDetails = await _service.GetByIdAsync(id);
            if (attendeeDetails == null) return View("NotFound");
            return View(attendeeDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, DOB, Address")] Attendee attendee)
        {
            if (!ModelState.IsValid) return View(attendee);
            if (id == attendee.Id)
            {
                await _service.UpdateAsync(id, attendee);
                TempData["Success"] = "Attendee updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(attendee);
        }

        //Get: Attendee Delete
        public async Task<IActionResult> Delete(int id)
        {
            var attendeeDetails = await _service.GetByIdAsync(id);
            if (attendeeDetails == null) return View("NotFound");
            return View(attendeeDetails);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var attendeeDetails = await _service.GetByIdAsync(id);
            if (attendeeDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            TempData["Success"] = "Attendee deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

KingsOwnInstitute/Controllers/OrganizersController.cs
using KingsOwnInstitute.Data.Services;
using KingsOwnInstitute.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KingsOwnInstitute.Controllers
{
    public class OrganizersController : Controller
    {
        private readonly IOrganizersService _service;
        public OrganizersController(IOrganizersService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allOrganizers = await _service.GetAllAsync();
            return View(allOrganizers);
        }

        //Get: Organizer Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, DOB, Address")] Organizer organizer)
        {
            if (!ModelState.IsValid)
            {
                return View(organizer);
            }
            await _service.AddAsync(organizer);
            TempData["Success"] = "Organizer added successfully";
            return RedirectToAction(nameof(Index));
        }

        //Get: Attendee Edit
        public async Task<IActionResult> Edit(int id)
        {
            var organizerDetails = await _service.GetByIdAsync(id);
            if (organizerDetails == null) return View("NotFound");
            return View(organizerDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, DOB, Address")] Organizer organizer)
        {
            if (!ModelState.IsValid) return View(organizer);
            if (id == organizer.Id)
            {
                await _service.UpdateAsync(id, organizer);
                TempData["Success"] = "Organizer updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(organizer);
        }

        //Get: Organizer Delete
        public async Task<IActionResult> Delete(int id)
        {
            var organizerDetails = await _service.GetByIdAsync(id);
            if (organizerDetails == null) return View("NotFound");
            return View(organizerDetails);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var organizerDetails = await _service.GetByIdAsync(id);
            if (organizerDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            TempData["Success"] = "Organizer deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

KingsOwnInstitute/Controllers/SeminarTypeController.cs
using KingsOwnInstitute.Data.Services;
using KingsOwnInstitute.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KingsOwnInstitute.Controllers
{
    public class SeminarTypeController : Controller
    {
        private readonly ISeminarTypeService _service;
        public SeminarTypeController(ISeminarTypeService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allSemType = await _service.GetAllAsync();
            return View(allSemType);
        }

        //Get: Organizer Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TypeName")] SeminarType semType)
        {
            if (!ModelState.IsValid)
            {
                return View(semType);
            }
            await _service.AddAsync(semType);
            TempData["Success"] = "Seminar Type added successfully";
            return RedirectToAction(nameof(Index));
        }

        //Get: Attendee Edit
        public async Task<IActionResult> Edit(int id)
        {
            var semTypeDetails = await _service.GetByIdAsync(id);
            if (semTypeDetails == null) return View("NotFound");
            return View(semTypeDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, TypeName")] SeminarType semType)
        {
            if (!ModelState.IsValid) return View(semType);
            if (id == semType.Id)
            {
                await _service.UpdateAsync(id, semType);
                TempData["Success"] = "Seminar Type updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(semType);
        }

        //Get: Organizer Delete
        public async Task<IActionResult> Delete(int id)
        {
            var semTypeDetails = await _service.GetByIdAsync(id);
            if (semTypeDetails == null) return View("NotFound");
            return View(semTypeDetails);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var semTypeDetails = await _service.GetByIdAsync(id);
            if (semTypeDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            TempData["Success"] = "Seminar Type deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

KingsOwnInstitute/Controllers/SeminarsController.cs
using KingsOwnInstitute.Data;
using KingsOwnInstitute.Models;
using KingsOwnInstitute.Data.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KingsOwnInstitute.Data.ViewModels;

namespace KingsOwnInstitute.Controllers
{
    public class SeminarsController : Controller
    {
        private readonly AppDBContext _context;
        private readonly ISeminarsService _service;
        public SeminarsController(AppDBContext context, ISeminarsService service)
        {
            _context = context;
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allSeminars = await _service.GetAllAsync(n => n.SeminarType);
            return View(allSeminars) ;
        }

        //Get: Seminars Create
        public async Task<IActionResult> Create()
        {
            var semTypeDropdownsData = await _service.GetSeminarDropdownsValues();
            ViewBag.SeminarTypes = new SelectList(semTypeDropdownsData.SeminarTypes, "Id", "TypeName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewSeminarViewModel seminar)
        {
            if (!ModelState.IsValid)
            {
                var semTypeDropdownsData = await _service.GetSeminarDropdownsValues();
                ViewBag.SeminarTypes = new SelectList(semTypeDropdownsData.SeminarTypes, "Id", "TypeName");
                return View(seminar);
            }
            await _service.AddNewSeminarAsync(seminar);
            TempData["Success"] = "Seminar added successfully";
            return RedirectToAction(nameof(Index));
        }

        //Get: Seminar Edit
        public async Task<IActionResult> Edit(int id)
        {
            var seminarDetails = await _service.GetSeminarByIdAysnc(id);
            if (seminarDetails == null) return View("NotFound");

            var response = new NewSeminarViewModel()
            {
                Id = seminarDetails.Id,
                SeminarTypeId = seminarDetails.SeminarTypeId,
                SeminarDate = seminarDetails.SeminarDate,
                Status = seminarDetails.Status,
            };
            var seminarDropdownsData = await _service.GetSeminarDropdownsValues();
            ViewBag.SeminarTypes = new SelectList(seminarDropdownsData.SeminarTypes, "Id", "TypeName");
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewSeminarViewModel seminar)
        {
            if (id != seminar.Id) return View("NotFound");
            if (!ModelState.IsValid)
            {
                var seminarDropdownsData = await _service.GetSeminarDropdownsValues();
                ViewBag.SeminarTypes = new SelectList(seminarDropdownsData.SeminarTypes, "Id", "TypeName");
                return View(seminar);
            }
            await _service.UpdateSeminarAsync(seminar);
            TempData["Success"] = "Seminar updated successfully";
            return RedirectToAction(nameof(Index));
        }

        //Get: Seminar Delete
        public async Task<IActionResult> Delete(int id)
        {
            var movieDetails = await _service.GetByIdAsync(id);
            if (movieDetails == null) return View("NotFound");
            return View(movieDetails);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movieDetails = await _service.GetByIdAsync(id);
            if (movieDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            TempData["Success"] = "Seminar deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

KingsOwnInstitute/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KingsOwnInstitute</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KingsOwnInstitute</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Attendees" asp-action="Index">Attendees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Organizers" asp-action="Index">Organizers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SeminarType" asp-action="Index">Seminar Type</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seminars" asp-action="Index">Seminars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SeminarOrganizers" asp-action="Index">Seminar Organizers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RegistrationInfo" asp-action="Index">Registration</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - KingsOwnInstitute - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>