KingsOwnInstitute/Models/RegistrationInfo.cs
using KingsOwnInstitute.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace KingsOwnInstitute.Models
{
    public class RegistrationInfo : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Attendee")]
        [ForeignKey("Attendee")]
        public int AttendeeId { get; set; }
        [ForeignKey("Seminar")]
        [Display(Name = "Seminar")]
        public int SeminarId { get; set; }
        [Display(Name = "Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime RegistrationDate { get; set; }

        public virtual Attendee Attendee { get; set; }
        public virtual Seminar Seminar { get; set; }
    }
}

KingsOwnInstitute/Controllers/RegistrationInfoController.cs
using KingsOwnInstitute.Data;
using KingsOwnInstitute.Data.Services;
using KingsOwnInstitute.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KingsOwnInstitute.Controllers
{
    public class RegistrationInfoController : Controller
    {
        private readonly AppDBContext _context;
        private readonly IRegistrationInfoService _service;
        public RegistrationInfoController(AppDBContext context, IRegistrationInfoService service)
        {
            _context = context;
            _service = service;
        }
        public IActionResult Index()
        {
            var allRegisterInfo = _context.RegistrationInfo
                .Include(a => a.Attendee)
                .Include(s => s.Seminar);
            return View(allRegisterInfo);
        }

        //Get: Registration
        public async Task<IActionResult> Create()
        {
            var registerDropdownsData = await _service.GetRegistrationDropdownsValues();
            ViewBag.Attendees = new SelectList(registerDropdownsData.Attendees, "Id", "Name");
            ViewBag.Seminars = new SelectList(registerDropdownsData.Seminars, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewRegistrationViewModel register)
        {
            if (!ModelState.IsValid)
            {
                var registerDropdownsData = await _service.GetRegistrationDropdownsValues();
                ViewBag.Attendees = new SelectList(registerDropdownsData.Attendees, "Id", "Name");
                ViewBag.Seminars = new SelectList(registerDropdownsData.Seminars, "Id", "Name");
                return View(register);
            }
            await _service.AddNewRegistrationAsync(register);
            TempData["Success"] = "Registered Attendee successfully";
            return RedirectToAction(nameof(Index));
        }

        //Get: Registration Edit
        public async Task<IActionResult> Edit(int id)
        {
            var registrationDetails = await _service.GetRegistrationByIdAysnc(id);
            if (registrationDetails == null) return View("NotFound");

            var response = new NewRegistrationViewModel()
            {
                Id = registrationDetails.Id,
                AttendeeId = registrationDetails.AttendeeId,
                SeminarId = registrationDetails.SeminarId,
                RegistrationDate = registrationDetails.RegistrationDate
            };
            var registerDropdownsData = await _service.GetRegistrationDropdownsValues();
            ViewBag.Attendees = new SelectList(registerDropdownsData.Attendees, "Id", "Name");
            ViewBag.Seminars = new SelectList(registerDropdownsData.Seminars, "Id", "Name");
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewRegistrationViewModel register)
        {
            if (id != register.Id) return View("NotFound");
            if (!ModelState.IsValid)
            {
                var registerDropdownsData = await _service.GetRegistrationDropdownsValues();
                ViewBag.Attendees = new SelectList(registerDropdownsData.Attendees, "Id", "Name");
                ViewBag.Seminars = new SelectList(registerDropdownsData.Seminars, "Id", "Name");
                return View(register);
            }
            await _service.UpdateRegistrationAsync(register);
            TempData["Success"] = "Registration updated successfully";
            return RedirectToAction(nameof(Index));
        }

        //Get: Registration Delete
        public async Task<IActionResult> Delete(int id)
        {
            var movieDetails = await _service.GetByIdAsync(id);
            if (movieDetails == null) return View("NotFound");
            return View(movieDetails);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movieDetails = await _service.GetByIdAsync(id);
            if (movieDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            TempData["Success"] = "Registration deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

KingsOwnInstitute/Views/RegistrationInfo/Create.cshtml
@model KingsOwnInstitute.Data.ViewModels.NewRegistrationViewModel

@{
    ViewData["Title"] = "Register Attendee";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="test-danger"></div>
            <div class="border p-3 mt-4 row">
                <div class="row pb-2">
                    <h2 class="text-primary">Register Attendee</h2>
                    <hr />
                </div>
                <div class="mb-3">
                    <label asp-for="AttendeeId" class="control-label"></label>
                    <select asp-for="AttendeeId" class="form-control" asp-items="ViewBag.Attendees">
                        <option disabled selected>--Select Attendee--</option>
                    </select>
                    <span asp-validation-for="AttendeeId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="SeminarId" class="control-label"></label>
                    <select asp-for="SeminarId" class="form-control" asp-items="ViewBag.Seminars">
                        <option disabled selected>--Select Seminar--</option>
                    </select>
                    <span asp-validation-for="SeminarId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="RegistrationDate" class="control-label"></label>
                    <input asp-for="RegistrationDate" type="date" class="form-control" />
                    <span asp-validation-for="RegistrationDate" class="text-danger"></span>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                    <a asp-controller="RegistrationInfo" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

KingsOwnInstitute/Views/RegistrationInfo/Delete.cshtml
@model RegistrationInfo

@{
    ViewData["Title"] = "Delete Registration";
}

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete @Model.Attendee.Name</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Attendee.Name" class="control-label"></label>
            <input asp-for="@Model.Attendee.Name" class="form-control" disabled />
            <span asp-validation-for="@Model.Attendee.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.Seminar.Name" class="control-label"></label>
            <input asp-for="@Model.Seminar.Name" class="form-control" disabled />
            <span asp-validation-for="@Model.Seminar.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="RegistrationDate" class="control-label"></label>
            <input asp-for="RegistrationDate" class="form-control" disabled />
            <span asp-validation-for="RegistrationDate" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-danger text-white" style="width: 150px">Delete</button>
        <a asp-controller="RegistrationInfo" asp-action="Index" class="btn btn-secondary" style="width: 150px">Back to List</a>
    </div>
</form>

KingsOwnInstitute/Views/RegistrationInfo/Edit.cshtml
@model KingsOwnInstitute.Data.ViewModels.NewRegistrationViewModel

@{
    ViewData["Title"] = "Update Registration";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="border p-3 mt-4 row">
                <div class="row pb-2">
                    <h2 class="text-primary">Update Registration</h2>
                    <hr />
                </div>
                <div class="mb-3">
                    <label asp-for="AttendeeId" class="control-label"></label>
                    <select asp-for="AttendeeId" class="form-control" asp-items="ViewBag.Attendees"></select>
                    <span asp-validation-for="AttendeeId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="SeminarId" class="control-label"></label>
                    <select asp-for="SeminarId" class="form-control" asp-items="ViewBag.Seminars"></select>
                    <span asp-validation-for="SeminarId" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="RegistrationDate" class="control-label"></label>
                    <input asp-for="RegistrationDate" type="date" class="form-control" />
                    <span asp-validation-for="RegistrationDate" class="text-danger"></span>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
                    <a asp-controller="RegistrationInfo" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

KingsOwnInstitute/Views/RegistrationInfo/Index.cshtml
@model IEnumerable<RegistrationInfo>

@{
    ViewBag.Title = "Index";
}

<div>
    <h1 class="text-center text-info fw-bold">Registrations</h1>
    <hr />
    @Html.ActionLink("Create New", "Create", null, new { @class = "button button-create" })
</div>
<br />
<table class="table text-center">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AttendeeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeminarId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </th>
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Attendee.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Seminar.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "button button-edit" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "button button-delete" })
            </td>
        </tr>
    }
</table>